feat: add promise article
shopee-sc/shopee-sc.github.io pull request #4
Opened 2019-09-04 11:37 UTC by LuckyWinty

add promise article

2019-09-09 10:29 UTC, beizhedenglong commented on website/blog/2019-09-04-promise.md
> +
写个简介， 加个 <!--truncate-->

2019-09-09 10:42 UTC, LuckyWinty commented on website/blog/2019-09-04-promise.md
> +
ok了...

2019-09-09 10:54 UTC, beizhedenglong requested changes

2019-09-09 10:54 UTC, beizhedenglong commented on website/blog/2019-09-04-promise.md
> +            this.then(onDone,onError)
onError 哪里来的？

2019-09-09 10:54 UTC, beizhedenglong commented on website/blog/2019-09-04-promise.md
> +            var args = Array.prototype.slice.call(arr);
all 是 `Promise` 上的一个静态方法

2019-09-09 10:54 UTC, beizhedenglong commented on website/blog/2019-09-04-promise.md
> +    } if (value && typeof value === 'object' && typeof value.then === 'function') {
else if?

2019-09-10 02:33 UTC, LuckyWinty commented on website/blog/2019-09-04-promise.md
> +            var args = Array.prototype.slice.call(arr);
不是用 class 写的，模拟不出静态方法吧

2019-09-10 02:33 UTC, LuckyWinty commented on website/blog/2019-09-04-promise.md
> +            this.then(onDone,onError)
我搞错了

2019-09-10 02:33 UTC, LuckyWinty commented on website/blog/2019-09-04-promise.md
> +    } if (value && typeof value === 'object' && typeof value.then === 'function') {
换行漏了

2019-09-17 03:32 UTC, beMySun approved these changes

2019-09-17 03:33 UTC, beMySun approved these changes

2019-09-17 03:33 UTC, merged